# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: arisara.km@gmail.com
brand: FonPlum
headline: Choreographer & Dancer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.facebook.com/fonplum.arisara" # the base hostname & protocol for your site
copyright: 2018 FonPlum, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 503237

# Contacts
email: arisara.km@gmail.com
phone: +66 92 4169392 

# Tracking
googleAnalitycsID: UA-83933844-1
